library(tidyverse)
library(limSolve)
library(abind)
args = commandArgs(trailingOnly=TRUE)
mychr=as.character(args[1])
myparfile = as.character(args[2])
mydir = as.character(args[3])
myoutdir = as.character(args[4])

source(myparfile)
source("scripts/haps2scan/scan_functions.R")
filein=paste0(mydir,"/R.haps.",mychr,".out.rds")
mydirout=paste0(mydir,"/",myoutdir)
dir.create(file.path(mydir,myoutdir))
fileout=paste0(mydirout,"/R.pseudoscan.",mychr,".txt")
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)
fileout_meansBySample=paste0(mydirout,"/R.meansBySample.",mychr,".txt")
source("scripts/haps2scan/haps2scan.Andreas.code.R")

